{
    "name": "E-commerce Connector Base",
    "version": "18.0.2.0.0",
    "category": "Sales",
    "summary": "Base models and tools for e-commerce sales synchronization",
    "Author": "Steven Bahaa",
    "website": "https://github.com/StevenBahaa/odoo18-ecommerce-sales-sync",
    "depends": [
        "base",
        "sale_management",
        "stock",
        "mail",
    ],
    "data": [
        "security/ecommerce_security.xml",
        "security/ir.model.access.csv",
        "data/ecommerce_sequence.xml",
        "views/ecommerce_store_views.xml",
        "views/ecommerce_webhook_event_views.xml",
        "views/ecommerce_external_order_views.xml",
        "views/ecommerce_external_order_line_views.xml",
        "views/ecommerce_customer_mapping_views.xml",
        "views/ecommerce_product_mapping_views.xml",
        "views/sale_order_views.xml",
        "views/ecommerce_menu.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
